### ISSUE TITLE
apply floor map  screen design

### ISSUE THREAD

**Issue by cOnigashima** [DroidKaigi/conference-app-2022#177]
**Idea Description**
apply floor map  screen design

**Reference images and links**
coming soon

**Comment by kubode** [comment]
✋ 


I have a few questions.

- Is this URL the correct screen design for the floor map?

    https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=1977%3A2763
    <img src="https://user-images.githubusercontent.com/5885032/190970416-7cffd6dc-583b-437a-8f78-799a3e97f2fb.png" width="240" />

- Does an API exist? Does it display an image of the asset? Or does it display an image of a specific URL?

- What happens when I tap this icon?

    ![image](https://user-images.githubusercontent.com/5885032/190971645-5348ee4a-b97d-4993-af38-6aefb029c2a2.png)

**Comment by takahirom** [comment]
The floor map image is decided.
I didn't notice the pin icon. I'll talk with the designer about it👀 .

**Comment by takahirom** [comment]
The pin icon is for zooming out to see the overview image. This image can be zoomed by pinching.
I think if you do this issue, you don't have to implement the icon first.

**Comment by kubode** [comment]
You may ignore this.

After implementing the design, I thought a bit about this specification.

My opinion is that the pin icon is unnecessary if all we want to do is zoom in on an image.
This is because the feature to zoom in on an image is usually done by tapping on the image itself.
Also, this icon <img src="https://user-images.githubusercontent.com/5885032/190971645-5348ee4a-b97d-4993-af38-6aefb029c2a2.png" width="16" /> is usually used to display the current location.

From the above, I think it is better to perform the feature of zooming in on an image when the image is tapped, and to turn off the icon.

**Comment by takahirom** [comment]
@kubode It makes sense, I'll talk with the designer about this. 🙏
