### ISSUE TITLE
Jump to DroidKaigi's twitter profile from the about screen

### ISSUE THREAD

**Issue by obaya884** [DroidKaigi/conference-app-2022#183]
**Idea Description**
Jump to [DroidKaigi's twitter profile page](https://twitter.com/DroidKaigi) with tapped twitter icon in the about screen

blocked by #181 

**Reference images and links**
<img src="https://user-images.githubusercontent.com/38175830/188361874-334054f7-0c27-4215-b40d-c546f61ee2ef.png" width=40% />

**Comment by Corvus400** [comment]
I would like to do this task.

**Comment by Corvus400** [comment]
@takahirom 
Let me ask you one question.
Do you have an Issue about the area circled in red?
![スクリーンショット 2022-09-06 0 37](https://user-images.githubusercontent.com/13657682/188485973-42cc23e6-f814-434f-94d3-fa90ba50fc04.png)

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
I think this issue will implement all the design of this screen. 
https://github.com/DroidKaigi/conference-app-2022/issues/181
So this issue will be just a click listener implementation.
But I think you can implement the three-links design. As long as you can implement fast. 😄 Because It can be implemented by the issue.
<img width="170" alt="image" src="https://user-images.githubusercontent.com/1386930/188486612-ba0f052f-5e1f-45c0-9d02-59bb33ba5b27.png">
