### ISSUE TITLE
Introduce multiplatform resource

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#259]
**Idea Description**

I would like to manage strings.

I tried moko-resource, but I couldn't solve the CI build error.

https://github.com/DroidKaigi/conference-app-2022/pull/119

limitation

* We can use it in Kotlin Multiplatform
* We can change it by locale. (EN/ JP etc)

**Reference images and links**

**Comment by kittinunf** [comment]
@takahirom The reason why it didn't work on CI because we use Ubuntu for our CI, moko-resouces throws error when the host is not macOS.

I did that in the past in my prev. company, when we change the host to macOS, it works well. 

Can we change the host to mac instead? If not, we won't be able to resolve the CI checks.

**Comment by takahirom** [comment]
I didn't know that 👀 
We can use GitHub Actions as much as we'd like. Because It's free for open source. 😄

**Comment by takahirom** [comment]
@kittinunf Do you want to try that?

**Comment by kittinunf** [comment]
I definitely can since I have done it before! But if we don't have macOS CI for github action (I think it is only in the paid plan), I don't think it is worth without CI checks.

**Comment by kittinunf** [comment]
In my experience, we shared Strings and Colors, it wasn't working with the Image resources though (but that was version 0.18.0 which was quite some time ago).

**Comment by takahirom** [comment]
I'm not sure if this problem is related to the host OS because the error message is `multiplatform_strings.xml: Error: Duplicate resources`.
I thought it is not related to the host 👀 
But probably we will need to try to build on Mac OS for iOS. That's for sure.
https://github.com/DroidKaigi/conference-app-2022/pull/119

**Comment by kittinunf** [comment]
How about if you could setup a macOS host for CI GitHub, I could help you with this one, what do you think?

**Comment by takahirom** [comment]
Do you mean we change this to `runs-on: macos-12` ?
https://github.com/DroidKaigi/conference-app-2022/blob/main/.github/workflows/Build.yml

**Comment by kittinunf** [comment]
👍 Thanks sounds like we can move ahead with this.

**Comment by kittinunf** [comment]
@takahirom @ry-itto I couldn't build the iOS project. It says that AssetColors file is not found (not generated by SwiftGen plugin).

Do you have any tick to make iOS working and/or runnable?

**Comment by kittinunf** [comment]
Ah, I got it, we need to run scripts under `app-ios/` folder first.

**Comment by ry-itto** [comment]
@kittinunf 
Sorry for lack of documentation about iOS build 🙇🏼 
In this iOS project, we need to run following before build whole app.

Some targets that depends on `SwiftGenPlugin` needs to build individualy before building a whole app.

I think this is Xcode 13.x bug because above workaround not needed on Xcode 14.0.

**Comment by takahirom** [comment]
@kittinunf I assigned this issue to you. Good luck! 👍

**Comment by kittinunf** [comment]
iOS seems to be tricky with the current setup. Let me think a bit on how we proceed with this.
